# Generated by Django 4.2.13 on 2024-06-22 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_contactform_alter_project_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
        migrations.AddField(
            model_name='project',
            name='project_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
