# Generated by Django 4.2.13 on 2024-06-29 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_project_image_project_project_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('intro', models.TextField()),
                ('image', models.ImageField(upload_to='owner_images/')),
            ],
        ),
    ]
