# Generated by Django 4.2.13 on 2024-06-29 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_ownerdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownerdetails',
            name='image',
        ),
        migrations.AddField(
            model_name='ownerdetails',
            name='about',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ownerdetails',
            name='hero_image_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ownerdetails',
            name='image_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
